FOLDER_TO_LABEL = {
    "Head-to-Knee_Forward_Bend_pose_or_Janu_Sirsasana_": "janu sirsasana",
    "Dolphin_Pose_or_Ardha_Pincha_Mayurasana_": "ardha pincha mayurasana",
    "Shoulder-Pressing_Pose_or_Bhujapidasana_": "bhujapidasana",
    "Corpse_Pose_or_Savasana_": "savasana",
    "Bridge_Pose_or_Setu_Bandha_Sarvangasana_": "setu bandha sarvangasana",
    "Standing_big_toe_hold_pose_or_Utthita_Padangusthasana": "utthita hasta padangustasana",
    "Legs-Up-the-Wall_Pose_or_Viparita_Karani_": "viparita karani",
    "Standing_Forward_Bend_pose_or_Uttanasana_": "uttanasana",
    "Warrior_II_Pose_or_Virabhadrasana_II_": "virabhadrasana ii",
    "Fish_Pose_or_Matsyasana_": "matsyasana",
    "Camel_Pose_or_Ustrasana_": "ustrasana",
    "Split pose": "hanumanasana",
    "Bow_Pose_or_Dhanurasana_": "dhanurasana",
    "Garland_Pose_or_Malasana_": "malasana",
    "Upward_Facing_Two-Foot_Staff_Pose_or_Dwi_Pada_Viparita_Dandasana_": "dwi pada viparita dandasana",
    "Child_Pose_or_Balasana_": "balasana",
    "Chair_Pose_or_Utkatasana_": "utkatasana",
    "Cockerel_Pose": "lolasana",
    "Warrior_I_Pose_or_Virabhadrasana_I_": "virabhadrasana i",
    "Lord_of_the_Dance_Pose_or_Natarajasana_": "natarajasana",
    "Tree_Pose_or_Vrksasana_": "vriksasana",
    "viparita_virabhadrasana_or_reverse_warrior_pose": "viparita virabhadrasana",
    "Locust_Pose_or_Salabhasana_": "salabhasana",
    "Half_Lord_of_the_Fishes_Pose_or_Ardha_Matsyendrasana_": "ardha matsyendrasana",
    "Revolved_Head-to-Knee_Pose_or_Parivrtta_Janu_Sirsasana_": "parivrtta janu sirsasana",
    "Pigeon_Pose_or_Kapotasana_": "kapotasana",
    "Scorpion_pose_or_vrischikasana": "vrischikasana",
    "Bound_Angle_Pose_or_Baddha_Konasana_": "baddha konasana",
    "Half_Moon_Pose_or_Ardha_Chandrasana_": "ardha chandrasana",
    "Staff_Pose_or_Dandasana_": "dandasana",
    "Eight-Angle_Pose_or_Astavakrasana_": "astavakrasana",
    "Side_Crane_(Crow)_Pose_or_Parsva_Bakasana_": "parsva bakasana",
    "Seated_Forward_Bend_pose_or_Paschimottanasana_": "paschimottanasana",
    "Extended_Revolved_Side_Angle_Pose_or_Utthita_Parsvakonasana_": "utthita parsvakonasana",
    "Downward-Facing_Dog_pose_or_Adho_Mukha_Svanasana_": "adho mukha svanasana",
    "Firefly_Pose_or_Tittibhasana_": "tittibhasana",
    "Wild_Thing_pose_or_Camatkarasana_": "camatkarasana",
    "Sitting pose 1 (normal)": "sukhasana",
    "Feathered_Peacock_Pose_or_Pincha_Mayurasana_": "pincha mayurasana",
    "Akarna_Dhanurasana": "akarna dhanurasana",
    "Four-Limbed_Staff_Pose_or_Chaturanga_Dandasana_": "chaturanga dandasana",
    "Gate_Pose_or_Parighasana_": "parighasana",
    "Handstand_pose_or_Adho_Mukha_Vrksasana_": "adho mukha vrksasana",
    "Standing_Split_pose_or_Urdhva_Prasarita_Eka_Padasana_": "urdhva prasarita eka padasana",
    "Supported_Headstand_pose_or_Salamba_Sirsasana_": "salamba sirsasana",
    "Side-Reclining_Leg_Lift_pose_or_Anantasana_": "anantasana",
    "Upward_Bow_(Wheel)_Pose_or_Urdhva_Dhanurasana_": "urdhva dhanurasana",
    "Frog_Pose_or_Bhekasana": "bhekasana",
    "Plow_Pose_or_Halasana_": "halasana",
    "Crane_(Crow)_Pose_or_Bakasana_": "bakasana",
    "Eagle_Pose_or_Garudasana_": "garudasana",
    "Wide-Legged_Forward_Bend_pose_or_Prasarita_Padottanasana_": "prasarita padottanasana",
    "Low_Lunge_pose_or_Anjaneyasana_": "anjaneyasana",
    "Cat_Cow_Pose_or_Marjaryasana_": "marjaryasana",
    "Supported_Shoulderstand_pose_or_Salamba_Sarvangasana_": "salamba sarvangasana",
    "Noose_Pose_or_Pasasana_": "pasasana",
    "Cow_Face_Pose_or_Gomukhasana_": "gomukhasana",
    "Reclining_Hand-to-Big-Toe_Pose_or_Supta_Padangusthasana_": "supta padangusthasana",
    "Pose_Dedicated_to_the_Sage_Koundinya_or_Eka_Pada_Koundinyanasana_I_and_II": "eka pada koundinyanasana",
    "Rajakapotasana": "rajakapotasana",
    "Dolphin_Plank_Pose_or_Makara_Adho_Mukha_Svanasana_": "makara adho mukha svanasana",
    "Happy_Baby_Pose_or_Ananda_Balasana_": "ananda balasana",
    "Supta_Baddha_Konasana_": "supta baddha konasana",
    "Upward_Plank_Pose_or_Purvottanasana_": "purvottanasana",
    "Peacock_Pose_or_Mayurasana_": "mayurasana",
    "Boat_Pose_or_Paripurna_Navasana_": "paripurna navasana",
    "Side_Plank_Pose_or_Vasisthasana_": "vasisthasana",
    "Extended_Puppy_Pose_or_Uttana_Shishosana_": "uttana shishosana",
    "Extended_Revolved_Triangle_Pose_or_Utthita_Trikonasana_": "utthita trikonasana",
    "Wind_Relieving_pose_or_Pawanmuktasana": "pawanmuktasana",
    "Wide-Angle_Seated_Forward_Bend_pose_or_Upavistha_Konasana_": "upavistha konasana",
    "Yogic_sleep_pose": "yoganidrasana",
    "Warrior_III_Pose_or_Virabhadrasana_III_": "virabhadrasana iii",
    "Virasana_or_Vajrasana": "virasana",
    "Heron_Pose_or_Krounchasana_": "krounchasana",
    "Plank_Pose_or_Kumbhakasana_": "phalakasana",
    "Scale_Pose_or_Tolasana_": "tolasana",
    "Cobra_Pose_or_Bhujangasana_": "bhujangasana",
    "Intense_Side_Stretch_Pose_or_Parsvottanasana_": "parsvottanasana",
    "Supta_Virasana_Vajrasana": "supta virasana",
    "Bharadvajas_Twist_pose_or_Bharadvajasana_I_": "bharadvajasana i",
    "Tortoise_Pose": "kurmasana",
}

def get_label(folder_name):
    return FOLDER_TO_LABEL.get(folder_name, folder_name.lower().replace("_", " ").strip())
